version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432"
  web:
    build: .
    command: "npm start"
    ports:
      - "8080:3001"
    env_file:
      - ./.env.prod
    depends_on:
      - db
networks:
  default:
    external:
      name: top-bridge-network
