version: "3.9"

services:
  web:
    build: .
    command: "npm start"
    ports:
      - "8888:3001"
    env_file:
      - ./.env.prod
    networks:
      - infrastructure
networks:
  infrastructure:
    name: top-infrastructure-network
